### ISSUE TITLE
Critical Exceptions (new source)

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#51]
I keep getting
<pre>MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader </pre>

<pre>

MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Yupi.Game.Achievements.AchievementManager.ProgressUserAchievement(GameClient session, String achievementGroup, UInt32 progressAmount, Boolean fromZero)
   at Yupi.Game.Rooms.User.RoomUserManager.OnUserAdd(RoomUser user)

Bug during user login: MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Yupi.Data.Base.Adapters.NormalQueryAdapter.GetRow()
   at Yupi.Game.Items.Interfaces.UserItem..ctor(UInt32 id, String baseName, String extraData, UInt32 group, String songCode)
   at Yupi.Game.Users.Factories.UserDataFactory.<>c.<GetUserData>b__0_11(<>f__AnonymousType10`2 <>h__TransparentIdentifier4)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Yupi.Game.Users.Factories.UserDataFactory.GetUserData(String sessionTicket, UInt32& errorCode)
   at Yupi.Game.GameClients.Interfaces.GameClient.TryLogin(String authTicket)

Bug during user login: MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Yupi.Data.Base.Adapters.NormalQueryAdapter.GetRow()
   at Yupi.Game.Items.Interfaces.UserItem..ctor(UInt32 id, String baseName, String extraData, UInt32 group, String songCode)
   at Yupi.Game.Users.Factories.UserDataFactory.<>c.<GetUserData>b__0_11(<>f__AnonymousType10`2 <>h__TransparentIdentifier4)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Yupi.Game.Users.Factories.UserDataFactory.GetUserData(String sessionTicket, UInt32& errorCode)
   at Yupi.Game.GameClients.Interfaces.GameClient.TryLogin(String authTicket)

Bug during user login: MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Yupi.Data.Base.Adapters.NormalQueryAdapter.GetRow()
   at Yupi.Game.Items.Interfaces.UserItem..ctor(UInt32 id, String baseName, String extraData, UInt32 group, String songCode)
   at Yupi.Game.Users.Factories.UserDataFactory.<>c.<GetUserData>b__0_11(<>f__AnonymousType10`2 <>h__TransparentIdentifier4)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Yupi.Game.Users.Factories.UserDataFactory.GetUserData(String sessionTicket, UInt32& errorCode)
   at Yupi.Game.GameClients.Interfaces.GameClient.TryLogin(String authTicket)

Bug during user login: MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Yupi.Data.Base.Adapters.NormalQueryAdapter.GetRow()
   at Yupi.Game.Items.Interfaces.UserItem..ctor(UInt32 id, String baseName, String extraData, UInt32 group, String songCode)
   at Yupi.Game.Users.Factories.UserDataFactory.<>c.<GetUserData>b__0_11(<>f__AnonymousType10`2 <>h__TransparentIdentifier4)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Yupi.Game.Users.Factories.UserDataFactory.GetUserData(String sessionTicket, UInt32& errorCode)
   at Yupi.Game.GameClients.Interfaces.GameClient.TryLogin(String authTicket)

Error during removing user from room:MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Yupi.Game.Rooms.User.RoomUserManager.RemoveUserFromRoom(GameClient session, Boolean notifyClient, Boolean notifyKick)

MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Yupi.Data.Base.Adapters.NormalQueryAdapter.GetRow()
   at Yupi.Game.Groups.GroupManager.GetGroup(UInt32 groupId)
   at Yupi.Game.Rooms.User.RoomUser.Serialize(ServerMessage message, Boolean gotPublicRoom)
   at Yupi.Game.Rooms.User.RoomUserManager.OnUserAdd(RoomUser user)
</pre>

**Comment by sant0ro** [comment]
Change DB Poolsize, i will try to search if this happens with me.

**Comment by ImNotSatan** [comment]
My poolsize is min:1 max:50

This has NEVER happend on the previous version.

**Comment by sant0ro** [comment]
Issue totally fixed yeah? Thanks for the FeedBack!
For your help of every time, your name will be added in Credits of Threads.

**Comment by ImNotSatan** [comment]
Sometimes still getting this Exception

<pre>
Bug during user login: MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Yupi.Data.Base.Adapters.NormalQueryAdapter.GetRow()
   at Yupi.Game.Items.Interfaces.UserItem..ctor(UInt32 id, String baseName, String extraData, UInt32 group, String songCode)
   at Yupi.Game.Users.Factories.UserDataFactory.<>c.<GetUserData>b__0_11(<>f__AnonymousType10`2 <>h__TransparentIdentifier4)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Yupi.Game.Users.Factories.UserDataFactory.GetUserData(String sessionTicket, UInt32& errorCode)
   at Yupi.Game.GameClients.Interfaces.GameClient.TryLogin(String authTicket)
</pre>
