### ISSUE TITLE
furnidata error

### ISSUE THREAD

**Issue by Zortex04** [sant0ro/Yupi#57]
hey another error here xD the 1.xml is a xml file and the directory is right but it still says

The XML content of the FurniData is in an invalid XML format, Details:

System.Xml.XmlException: An XML comment cannot contain '--', and '-' cannot be the last character. Line 9, position 7.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type, Int32& outStartPos, Int32& outEndPos)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type)
   at System.Xml.XmlTextReaderImpl.ParseComment()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at Yupi.Data.FurnitureDataManager.SetCache(Boolean forceReload) in C:\Users\Tonny\Desktop\Yupi-master\Yupi\Data\FurnitureDataManager.cs:line 74

**Comment by sant0ro** [comment]
This is only with you. 
You don't know how to use Yupi.
And don't have valid SWF pack.

**Comment by sant0ro** [comment]
See if your're using IIS and IIS has XML Wrapping and Mime Type.
Really weird. Show me what appear in browser.
